//! The pnpm backend for pmpx.
//!
//! Pure mapping: a verb plus its arguments in, one command out. It reads nothing, writes
//! nothing, and never looks at the environment -- everything the plugin is allowed to know
//! arrives in [`Context`], which the host filled in from files it already stat'd.

use std::ffi::OsString;

use pmpx_plugin::{CommandSpec, Context, Family, PackageManager, PluginError, Verb};

struct Pnpm;

impl PackageManager for Pnpm {
    fn name(&self) -> &str {
        "pnpm"
    }

    fn family(&self) -> Family {
        Family::NODE
    }

    fn command(
        &self,
        _ctx: &Context,
        verb: Verb,
        args: &[OsString],
    ) -> Result<CommandSpec, PluginError> {
        let spec = match verb {
            // No argument means "install what the lockfile already says". With arguments it is
            // "add these", the same split npm makes.
            Verb::Install if args.is_empty() => CommandSpec::new("pnpm").arg("install"),
            Verb::Install => CommandSpec::new("pnpm").arg("add").args(args.iter()),

            Verb::Remove => CommandSpec::new("pnpm").arg("remove").args(args.iter()),

            // pnpm's `run` takes the script name as its first positional argument, and that is
            // exactly the shape the host hands over: `[target, ...rest]` already flattened into
            // one list, the target first. So the whole list is passed on unchanged and the
            // target needs no special case.
            //
            // No `--` is inserted, and pnpm is the opposite of npm and cargo here. pnpm hands
            // arguments to the script exactly as it received them, so a `--` would be handed
            // over too -- measured:
            //
            //     $ pnpm run probe --foo
            //     GOT:--foo                 (the option-shaped argument reaches the script)
            //
            //     $ pnpm run probe -- --foo
            //     GOT:--,--foo              (the `--` itself arrives as an argument)
            Verb::Run => CommandSpec::new("pnpm").arg("run").args(args.iter()),

            // `build` and `test` name scripts the same way, and pnpm forwards their arguments
            // the same way, so the same "no `--`" applies.
            Verb::Build => CommandSpec::new("pnpm").arg("build").args(args.iter()),
            Verb::Test => CommandSpec::new("pnpm").arg("test").args(args.iter()),

            // `pnpm update` takes package names as positional arguments, so no `-p` is needed.
            Verb::Update if args.is_empty() => CommandSpec::new("pnpm").arg("update"),
            Verb::Update => CommandSpec::new("pnpm").arg("update").args(args.iter()),

            // pnpm has a real `exec` subcommand -- it runs a binary out of `node_modules/.bin` --
            // so this verb maps onto it instead of being reported unsupported.
            Verb::Exec => CommandSpec::new("pnpm").arg("exec").args(args.iter()),
        };

        Ok(spec)
    }
}

/// The factory that the wrapper crate generated by crate-plugin-kit calls.
pub fn create() -> Box<dyn PackageManager> {
    Box::new(Pnpm)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The context a host would hand over: the project root and the files it matched.
    ///
    /// Built through [`Context::builder`] rather than as a struct literal: the v3 context carries
    /// fields a plugin never sets (pins, reason, score, the declared files) and a lifetime, so the
    /// literal the v2 tests used no longer compiles -- and should not, since a plugin that fills
    /// those in by hand would be inventing what the host decides.
    fn ctx() -> Context<'static> {
        Context::builder()
            .project_root("/tmp/proj")
            .matched(["package.json", "pnpm-lock.yaml"])
            .build()
    }

    /// The exact argv the backend gets spawned with, program first.
    fn argv(verb: Verb, args: &[&str]) -> Vec<String> {
        let args: Vec<OsString> = args.iter().map(OsString::from).collect();
        let spec = Pnpm.command(&ctx(), verb, &args).expect("should map");
        std::iter::once(spec.program.to_string_lossy().into_owned())
            .chain(spec.args.iter().map(|a| a.to_string_lossy().into_owned()))
            .collect()
    }

    #[test]
    fn install_without_arguments_installs_what_the_lockfile_says() {
        assert_eq!(argv(Verb::Install, &[]), ["pnpm", "install"]);
    }

    #[test]
    fn install_with_arguments_adds_dependencies() {
        assert_eq!(
            argv(Verb::Install, &["lodash", "vitest"]),
            ["pnpm", "add", "lodash", "vitest"]
        );
    }

    #[test]
    fn remove_removes_dependencies() {
        assert_eq!(
            argv(Verb::Remove, &["lodash"]),
            ["pnpm", "remove", "lodash"]
        );
    }

    /// The host hands `run` the script name first, so the name is already where pnpm wants it and
    /// every argument follows unchanged.
    #[test]
    fn run_forwards_the_script_name_and_its_arguments() {
        assert_eq!(
            argv(Verb::Run, &["build", "--filter", "web"]),
            ["pnpm", "run", "build", "--filter", "web"]
        );
        assert_eq!(argv(Verb::Run, &[]), ["pnpm", "run"]);
    }

    /// The one place pnpm is the opposite of npm and cargo, pinned with an option-shaped argument
    /// so an inserted `--` cannot hide. See the table in the `run` arm for the two measurements.
    #[test]
    fn no_double_dash_is_inserted_before_the_arguments() {
        assert_eq!(
            argv(Verb::Run, &["probe", "--foo"]),
            ["pnpm", "run", "probe", "--foo"]
        );
        assert_eq!(argv(Verb::Build, &["--foo"]), ["pnpm", "build", "--foo"]);
        assert_eq!(argv(Verb::Test, &["--foo"]), ["pnpm", "test", "--foo"]);
    }

    /// The listing only states what it does with what it is given: a `--` that arrives from the
    /// caller is passed on, not stripped and not doubled.
    #[test]
    fn an_explicit_double_dash_is_forwarded_unchanged() {
        assert_eq!(
            argv(Verb::Run, &["probe", "--", "--foo"]),
            ["pnpm", "run", "probe", "--", "--foo"]
        );
    }

    /// A guard over every verb at once: no mapping may contain a `--`. npm and cargo both need
    /// one somewhere, which is what makes this the mistake most likely to be copied in.
    #[test]
    fn no_mapping_ever_inserts_a_double_dash() {
        let args = [OsString::from("probe"), OsString::from("--foo")];
        for verb in Verb::ALL {
            let spec = Pnpm
                .command(&ctx(), *verb, &args)
                .unwrap_or_else(|e| panic!("{verb} should map: {e}"));
            assert!(
                !spec.args.iter().any(|a| a == "--"),
                "{verb} inserted a `--`: {:?}",
                spec.args
            );
        }
    }

    #[test]
    fn build_forwards_its_arguments() {
        assert_eq!(
            argv(Verb::Build, &["--mode", "production"]),
            ["pnpm", "build", "--mode", "production"]
        );
        assert_eq!(argv(Verb::Build, &[]), ["pnpm", "build"]);
    }

    #[test]
    fn test_forwards_its_arguments() {
        assert_eq!(argv(Verb::Test, &["--watch"]), ["pnpm", "test", "--watch"]);
        assert_eq!(argv(Verb::Test, &[]), ["pnpm", "test"]);
    }

    #[test]
    fn update_takes_package_names_positionally() {
        assert_eq!(argv(Verb::Update, &[]), ["pnpm", "update"]);
        assert_eq!(
            argv(Verb::Update, &["lodash"]),
            ["pnpm", "update", "lodash"]
        );
    }

    /// Unlike cargo, pnpm really does have an `exec`, so there is nothing to degrade here.
    #[test]
    fn exec_runs_a_binary_from_the_project() {
        assert_eq!(
            argv(Verb::Exec, &["eslint", "."]),
            ["pnpm", "exec", "eslint", "."]
        );
    }
    /// The text files a host and the release tool read must agree with the crate and the contract:
    /// the manifest's `name`/`family`/`version`/`abi`, and the entry symbol the release workflow
    /// hands to `plugin-asset`.
    ///
    /// No compiler checks any of these, and they are trusted: a stale `abi` is how a plugin ends up
    /// "installed but refused", and a stale `entry_symbol` is how a release fails *after* it has
    /// published. The check is deliberately a text one -- a TOML or YAML parser would be this
    /// crate's only dependency, and the MSRV job builds `--all-targets`.
    #[test]
    fn the_manifest_and_the_release_workflow_agree_with_the_contract() {
        // Spaces dropped on both sides so the check does not care how the files are aligned.
        let manifest = std::fs::read_to_string("pmpx-plugin.toml")
            .expect("the manifest should be readable")
            .replace(' ', "");
        let cargo = std::fs::read_to_string("Cargo.toml")
            .expect("Cargo.toml should be readable")
            .replace(' ', "");

        let checked = [
            ("name", format!("name=\"{}\"", Pnpm.name())),
            ("family", format!("family=\"{}\"", Pnpm.family().as_str())),
            (
                "version",
                format!("version=\"{}\"", env!("CARGO_PKG_VERSION")),
            ),
            ("abi", format!("abi={}", pmpx_plugin::abi::PMPX_ABI_MAJOR)),
        ];

        for (what, wanted) in checked {
            assert!(
                manifest.contains(&wanted),
                "the manifest must declare `{wanted}` for {what}; it says:\n{manifest}"
            );

            if what == "version" {
                assert!(
                    cargo.contains(&wanted),
                    "Cargo.toml must declare `{wanted}` too, or the store reports a version this crate does not have"
                );
            }
        }

        let release = std::fs::read_to_string(".github/workflows/release.yaml")
            .expect("the release workflow should be readable")
            .replace(' ', "");
        let symbol = format!("entry_symbol:{}", pmpx_plugin::abi::PMPX_ENTRY_SYMBOL);
        assert!(
            release.contains(&symbol),
            "release.yaml must pass `{symbol}` to the asset tool, or the release fails after publishing"
        );
    }
}
